version: '3'

vars:
  COMPOSE_FILE: deploy/compose.yaml
  ENV_FILE: .env

tasks:
  infra:up:
    desc: Up infra services
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} --env-file {{.ENV_FILE}} up -d

  infra:down:
    desc: Stop and remove infra services
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} --env-file {{.ENV_FILE}} down -v --rmi local

  db:up:
    desc: Up db service
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} --env-file {{.ENV_FILE}} up db -d --no-deps

  db:down:
    desc: Down db service
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} --env-file {{.ENV_FILE}} down db

  kratos:up:
    desc: Up kratos service
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} --env-file {{.ENV_FILE}} up kratos -d --no-deps

  kratos:down:
    desc: Down kratos service
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} --env-file {{.ENV_FILE}} down kratos

  client:dev:
    desc: Start client in dev mode
    cmds:
      - npm run dev -w=apps/client

  client:eslint:inspect:
    desc: Inspect eslint configuration
    cmds:
      - npm run eslint:inspect -w=apps/client

  client:eslint:check:
    desc: Check lint files
    cmds:
      - npm run eslint:check -w=apps/client

  server:dev:
    desc: Start server in dev mode
    cmds:
      - npm run dev -w=apps/server

  server:eslint:inspect:
    desc: Inspect eslint configuration
    cmds:
      - npm run eslint:inspect -w=apps/server

  server:eslint:check:
    desc: Check lint files
    cmds:
      - npm run eslint:check -w=apps/server
