version: '3'

vars:
  COMPOSE_FILE: deploy/compose.yaml
  ENV_FILE: .env

tasks:
  db:up:
    desc: Up db service
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} --env-file {{.ENV_FILE}} up db -d

  auth:up:
    desc: Up kratos service
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} --env-file {{.ENV_FILE}} up kratos -d

  server:dev:
    desc: Start server in dev mode
    cmds:
      - npm run dev -w=apps/server

  down:
    desc: Stop and remove all services
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} --env-file {{.ENV_FILE}} down -v --rmi local
