version: '3'

vars:
  COMPOSE_FILE: deploy/compose.yaml
  ENV_FILE: .env

tasks:
  core:up:
    desc: Up core services
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} --env-file {{.ENV_FILE}} up -d

  core:down:
    desc: Stop and remove core services
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} --env-file {{.ENV_FILE}} down -v --rmi local

  db:up:
    desc: Up db service
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} --env-file {{.ENV_FILE}} up db -d --no-deps

  db:down:
    desc: Down db service
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} --env-file {{.ENV_FILE}} down db

  kratos:up:
    desc: Up kratos service
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} --env-file {{.ENV_FILE}} up kratos -d --no-deps

  kratos:down:
    desc: Down kratos service
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} --env-file {{.ENV_FILE}} down kratos
  
  client:dev:
    desc: Start client in dev mode
    cmds:
      - npm run dev -w=services/client

  server:dev:
    desc: Start server in dev mode
    cmds:
      - npm run dev -w=services/server
